In [2]:
import torchvision
import torch

train_dataset = torchvision.datasets.Imagenette(root='./data/imagenette',
                                                split = 'train',                
                                                download = True
                                                )

AttributeError: module 'torchvision.datasets' has no attribute 'Imagenette'

In [11]:
import torch
from torchvision.transforms import ToTensor

train = torchvision.datasets.SVHN(root='./data/SVHN',
                          split='train',
                          download=True,
                          transform=ToTensor())

ood_test_data = torchvision.datasets.CIFAR10(
        root="data/CIFAR10",
        train=False,
        download=True,
        transform=ToTensor()
    ) 

Using downloaded and verified file: ./data/SVHN\train_32x32.mat
Files already downloaded and verified


In [8]:
from utils.metrics import *
_,targets = next(iter(DataLoader(train,len(train))))
print(targets)

tensor([1, 9, 2,  ..., 1, 6, 9])


In [13]:
print(torch.tensor(ood_test_data.targets))

tensor([3, 8, 8,  ..., 5, 1, 7])


In [2]:
import torch
torch.manual_seed(0)
torch.randn(100)

tensor([-1.1258e+00, -1.1524e+00, -2.5058e-01, -4.3388e-01,  8.4871e-01,
         6.9201e-01, -3.1601e-01, -2.1152e+00,  3.2227e-01, -1.2633e+00,
         3.4998e-01,  3.0813e-01,  1.1984e-01,  1.2377e+00,  1.1168e+00,
        -2.4728e-01, -1.3527e+00, -1.6959e+00,  5.6665e-01,  7.9351e-01,
         5.9884e-01, -1.5551e+00, -3.4136e-01,  1.8530e+00,  7.5019e-01,
        -5.8550e-01, -1.7340e-01,  1.8348e-01,  1.3894e+00,  1.5863e+00,
         9.4630e-01, -8.4368e-01, -6.1358e-01,  3.1593e-02, -4.9268e-01,
         2.4841e-01,  4.3970e-01,  1.1241e-01,  6.4079e-01,  4.4116e-01,
        -1.0231e-01,  7.9244e-01, -2.8967e-01,  5.2507e-02,  5.2286e-01,
         2.3022e+00, -1.4689e+00, -1.5867e+00, -6.7309e-01,  8.7283e-01,
         1.0554e+00,  1.7784e-01, -2.3034e-01, -3.9175e-01,  5.4329e-01,
        -3.9516e-01, -4.4622e-01,  7.4402e-01,  1.5210e+00,  3.4105e+00,
        -1.5312e+00, -1.2341e+00,  1.8197e+00, -5.5153e-01, -5.6925e-01,
         9.1997e-01,  1.1108e+00,  1.2899e+00, -1.4

In [14]:

_,targets = next(iter(DataLoader(ood_test_data,len(ood_test_data))))
print(targets)

tensor([3, 8, 8,  ..., 5, 1, 7])


In [39]:
loader = torch.utils.data.DataLoader(train,len(train))
train_set,_ = next(iter(loader))

train_set.mean((0,2,3))

tensor([0.4377, 0.4438, 0.4728])

In [14]:
train = torchvision.datasets.CIFAR10(root='./data/CIFAR10',
                          train=True,
                          download=True,
                          transform=ToTensor())

100%|██████████| 170498071/170498071 [00:13<00:00, 12887125.91it/s]


Extracting ./data/CIFAR10\cifar-10-python.tar.gz to ./data/CIFAR10


In [25]:
loader = torch.utils.data.DataLoader(train,len(train))
train_set,_ = next(iter(loader))

In [35]:
train_set.std((0,2,3))

tensor([0.2470, 0.2435, 0.2616])

In [31]:
from tqdm import tqdm, trange
from random import random, randint
from time import sleep

with trange(10) as t:
    for i in t:
        # Description will be displayed on the left
        t.set_description('GEN %i' % i)
        # Postfix will be displayed on the right,
        # formatted automatically based on argument's datatype
        metrics = {'loss': random(),
                   'gen': randint(1,999),
                   'str': 'h',
                   'lst': [1,2]}
        t.set_postfix(metrics)
        # t.set_postfix(loss=random(), gen=randint(1,999), str='h',
        #               lst=[1, 2])
        sleep(0.1)

with tqdm(total=10, bar_format="{postfix[0]} {postfix[1][value]:>8.2g}",
          postfix=["Batch", {"value": 0}]) as t:
    for i in range(10):
        sleep(0.1)
        t.postfix[1]["value"] = i / 2
        t.update()

GEN 9: 100%|██████████| 10/10 [00:01<00:00,  9.60it/s, loss=0.815, gen=454, str=h, lst=[1, 2]]
Batch      4.5


In [18]:
from tqdm import tqdm
class TqdmExtraFormat(tqdm):
    """Provides a `total_time` format parameter"""
    @property
    def format_dict(self):
        d = super().format_dict
        total_time = d["elapsed"] * (d["total"] or 0) / max(d["n"], 1)
        d.update(total_time=self.format_interval(total_time) + " in total")
        return d

for i in TqdmExtraFormat(
      range(9), ascii=" .oO0",
      bar_format="{total_time}: {percentage:.0f}%|{bar}{r_bar}"):
    if i == 4:
        break

00:00 in total: 44%|0000.     | 4/9 [00:00<?, ?it/s]


In [32]:
epochs = 500

t = range(500)

for ti in t:
    if ti % (epochs // 10) == 0:
        print(ti)

0
50
100
150
200
250
300
350
400
450
